<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="2.0" 
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:sitemap="http://www.sitemaps.org/schemas/sitemap/0.9"
                xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <xsl:output method="html" version="1.0" encoding="UTF-8" indent="yes"/>
  <xsl:template match="/">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <title>XML Sitemap - We Love Vilamoura</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <style type="text/css">
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen-Sans, Ubuntu, Cantarell, "Helvetica Neue", sans-serif;
            color: #333;
            margin: 0;
            padding: 2rem;
          }
          a {
            color: #0066cc;
            text-decoration: none;
          }
          a:hover {
            text-decoration: underline;
          }
          table {
            border-collapse: collapse;
            width: 100%;
            margin: 2rem 0;
          }
          th {
            background-color: #f4f4f4;
            text-align: left;
            padding: 1rem;
            font-weight: bold;
          }
          td {
            padding: 1rem;
            border-bottom: 1px solid #eee;
          }
          h1 {
            color: #333;
            font-size: 2rem;
            margin-bottom: 1rem;
          }
          .header {
            background-color: #003366;
            color: white;
            padding: 2rem;
            margin: -2rem -2rem 2rem -2rem;
          }
          .header h1 {
            color: white;
            margin: 0;
          }
          .meta {
            color: #666;
            font-size: 0.875rem;
          }
          .priority-high {
            color: #2ecc71;
          }
          .priority-medium {
            color: #f1c40f;
          }
          .priority-low {
            color: #95a5a6;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>We Love Vilamoura Sitemap</h1>
          <p>Generated by Clever Details</p>
        </div>
        <div>
          <p>
            This sitemap contains <xsl:value-of select="count(sitemap:urlset/sitemap:url)"/> URLs.
          </p>
          <table>
            <tr>
              <th>URL</th>
              <th>Images</th>
              <th>Priority</th>
              <th>Change Frequency</th>
              <th>Last Modified</th>
            </tr>
            <xsl:for-each select="sitemap:urlset/sitemap:url">
              <tr>
                <td>
                  <a href="{sitemap:loc}"><xsl:value-of select="sitemap:loc"/></a>
                </td>
                <td>
                  <xsl:value-of select="count(image:image)"/>
                </td>
                <td>
                  <xsl:variable name="priority">
                    <xsl:value-of select="sitemap:priority"/>
                  </xsl:variable>
                  <xsl:choose>
                    <xsl:when test="$priority &gt;= 0.9">
                      <span class="priority-high"><xsl:value-of select="$priority"/></span>
                    </xsl:when>
                    <xsl:when test="$priority &gt;= 0.7">
                      <span class="priority-medium"><xsl:value-of select="$priority"/></span>
                    </xsl:when>
                    <xsl:otherwise>
                      <span class="priority-low"><xsl:value-of select="$priority"/></span>
                    </xsl:otherwise>
                  </xsl:choose>
                </td>
                <td><xsl:value-of select="sitemap:changefreq"/></td>
                <td><xsl:value-of select="sitemap:lastmod"/></td>
              </tr>
            </xsl:for-each>
          </table>
        </div>
      </body>
    </html>
  </xsl:template>
</xsl:stylesheet> 